### ISSUE TITLE
Could "Move to first / next" look beyond the line?

### ISSUE THREAD

**Issue by aaronmw** [Gruntfuggly/better-cursors#1]
I want each of my cursors to look forward until they find an instance of $needle, then move to and select that instance.

Just a request. Thanks, regardless 👍

**Comment by Gruntfuggly** [comment]
Yes, I don't see why not - is there no way to do that built into vscode already?

**Comment by Gruntfuggly** [comment]
The latest version now has a configuration setting, `better-cursors.scope`. By default this is set to `line` which is the current behaviour. If you set it to `document` it will keep searching the rest of the document.

Note - at the moment it's not clever enough to move cursors past found terms, so if the next instance of your search is past all the cursors, they will all end up at the same place.
