### ISSUE TITLE
Select text while moving cursors?

### ISSUE THREAD

**Issue by dkyleward** [Gruntfuggly/better-cursors#2]
I've got 3 cursors at the start of the line, and I want to select everything to the first comma on each line. Your package is definitely the closest I've found, but I'm hoping you can support selection in addition to moving. (I've tried dumb stuff like holding shift while clicking "Move cursor to next".)

Thanks!

**Comment by Gruntfuggly** [comment]
Hi - I did think of adding something like that, but I wasn't completely sure how to do it. My first thought was what you describe (holding down the shift key) but I don't think there is any way to detect keyboard modifiers - you can't actually intercept key presses. So the alternative would be adding 'select to' commands as well as 'move to', and I thought there might end up being too many.

It seems like it might be the way to go though, as I have the same need sometimes...

**Comment by Gruntfuggly** [comment]
I've added two new commands to move to the next/previous with select:
`Move Cursors To Next With Select`
`Move Cursors To Previous With Select`

Let me know how you get on.

**Comment by dkyleward** [comment]
It works perfectly. Thanks!
